[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor="#161f36"
backgroundColor="#f2ede2"
secondaryBackgroundColor="#bacbd8"
textColor="#000000"
font="sans serif"
linkColor = "#598392"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[ui]
hideTopBar = false
