[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#aec3b0"
secondaryColor = "#124559"
backgroundColor = "#fffcf8"
secondaryBackgroundColor = "#aec3b0"
textColor = "#124559"
font = "sans serif"
linkColor = "#598392"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[ui]
hideTopBar = false
